functionality for getting all reviews added
melsem08/frontend_games pull request #1
Opened 2023-05-30 15:13 UTC by melsem08

2023-05-30 15:52 UTC, Keb84 requested changes
Great work on this ticket so far 🎉 please have a look at the suggestions and resubmit a PR 🙂

2023-05-30 15:52 UTC, Keb84 commented on src/components/ReviewsList.jsx
> +  const [reviews, setReviews] = useState([]);
some state for loading would be good here 👀 to give the use some visual feedback while the page is rendering

2023-05-30 15:52 UTC, Keb84 commented on src/components/ReviewsList.jsx
> +            </li>
I would consider also displaying the image for each review 💭

2023-05-30 15:52 UTC, Keb84 commented on utils.js
> +    }
Great that you've put your api calls into a utils file 🤸

2023-05-31 08:07 UTC, MrMcSnail approved these changes
Looks good! Merge away!

2023-05-31 08:10 UTC, merged